In [34]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:14px;}
</style>
"""))

<font color="red" size ="6"><b>ch14. 웹 데이터 수집</b></font>
# 1절.BeautifulSoup 과 parser
    (정적 웹크롤링, 공공api사용)
    
 `pip install bs4`아나콘다를 설치하면 자동 설치되는 패키지에 포함
 
- 공식 사이트 : https://www.crummy.com/software/BeautifulSoup/
- Documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [35]:
import requests # HTTP 요청 처리하는 lib
# file://==c:
#http://www.
from requests_file import FileAdapter

In [36]:
# 로컬에 있는 파일을 웹요청하듯이 읽어오는 작업 
s=requests.Session()
s.mount("file://", FileAdapter())#file://로 시작하는 url을 어댑터가 처리
response =s.get("file:///ai/lecNote/01_python/data/ch14_sample.html")#c:/ai/lecNote/data/ch14_sample.html
response

In [37]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [13]:
response.status_code
#200:정상
#404:없는 페이지

200

In [38]:
response.content #html의 binary형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [39]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [17]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [20]:
#html 파싱 객체 
from bs4 import BeautifulSoup
soup =BeautifulSoup(response.text, #response.content,
                   "html.parser")
#soup.__str__()
#soup

In [30]:
#soup.select_one('선택자'): 해당 선택자 처음 하나 엘리먼트만 
el=soup.select_one('h1.css')
print('el=', el)
print('el.text   =>', el.text)
print('el.string =>', el.string)
print('el의 속성들 =>', el.attrs)
print('el의 class 속성 =>', el.attrs['class'])
print('el의 class 속성 =>', el.attrs.get('class'))
print('el의 href속성 =>', el.attrs.get('href'))
print('el의 name=>', el.name)

el= <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text   => Hello, CSS
el.string => Hello, CSS
el의 속성들 => {'class': ['greeting', 'css'], 'id': 'text'}
el의 class 속성 => ['greeting', 'css']
el의 class 속성 => ['greeting', 'css']
el의 href속성 => None
el의 name=> h1

In [40]:
#2. soup.select_one('선택자'): 해당 선택자 엘리먼트 다 배열로
els = soup.select('h1.css')
print('els=>', els)
print('els들의 text =>',[el.text for el in els])
print('els들의 string =>',[el.string for el in els])
print('els들의 속성들 =>',[el.attrs for el in els])
print('els들의 class 속성 =>',[el.attrs.get('class') for el in els])

els=> [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text => ['Hello, CSS', 'Hi, CSS']
els들의 string => ['Hello, CSS', 'Hi, CSS']
els들의 속성들 => [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class 속성 => [['greeting', 'css'], ['css']]

In [43]:
#3.soup.find('태그, 속성') vs soup.select_one('선택자'): 해당 속성을 갖고있는 태그 처음 하나만
print('selct_one:', soup.select_one('h1.css'))
print('find     :', soup.find('h1', {'class':'css'}))
print('find     :', soup.find('h1', class_='css'))
print()
print('select_one:',soup.select_one('h1#text'))
print('select_one:', soup.find('h1', {'id':'text'}))

selct_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
find     : <h1 class="greeting css" id="text">Hello, CSS</h1>
find     : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>

In [50]:
#4. soup.find_all(태그, 속성)vs soup.select ('선택자') :해당 엘리먼트 다 list로
#print('모든 h1.css와 span태그:', soup.select('h1.css, span'))
print('모든 h1.css.greeting와 span태그:', soup.select('h1.css.greeting, span'))
print('모든 h1.css.greeting와 span태그:', soup.find_all(['h1'],class_='css') +
                                        soup.find_all('span'))

모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [53]:
# 없는 엘리먼트 찾기 
print('find_all(빈list):', soup.find_all('a'))
print('find(None)      :', soup.find('a'))
print('select(빈list)   :', soup.select('a'))
print('select_one(None):', soup.select_one('a'))

find_all(빈list): []
find(None)      : None
select(빈list)   : []
select_one(None): None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup모듈을 활용한 html 웹데이터 수집
### 1)환율정보 가져오기 (네이버증권> 시장지표)

- https://finance.naver.com/marketindex/

    * 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인할 수 있음
        - Allow : 크롤링 허용가능한 폴더 
        - Disallow:크롤링 제한 폴더

In [60]:
# soup 객체 만드는 방법1
import requests
from bs4 import BeautifulSoup
url='https://finance.naver.com/marketindex/'
response=requests.get(url)
response #response 객체 
print(response.status_code)
#print(response.text) #response.content
soup=BeautifulSoup(response.text, 'html.parser')

200

In [66]:
# soup 객체 만드는 방법2
from urllib.request import urlopen
url='https://finance.naver.com/marketindex/'
response=urlopen(url)
response #HTTPResponse
print(response.status)
#print(response.read().decode('cp949'))
soup =BeautifulSoup(response, 'html.parser')

200

In [77]:
p='1,417,000.70'
float(p.replace(',',''))#방법1
float(''.join(p.split(','))) #방법2

1417000.7

In [82]:
# div.head_info 밑의 span.value(find계열)
prices=[]
headinfos=soup.find_all('div',class_='head_info')
for headinfo in headinfos:
    #print(headinfo)
    price=headinfo.find('span',class_='value')
    prices.append(float(''.join((price.text.split(',')))))
print (prices)

[1417.7, 889.17, 1635.6, 210.09, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.92, 4441.1, 200855.05]

In [83]:
# span.value(find 계열)
price_els=soup.find_all('span', class_='value')
prices=[round(float(price.text.replace(',','')),1)for price in price_els]
print(prices)

[1417.7, 889.2, 1635.6, 210.1, 159.2, 1.2, 1.4, 99.7, 83.2, 1863.9, 4441.1, 200855.0]

In [86]:
# div.head_info 밑의 span.value
price_els=soup.select('div.head_info > span.value')
#price_els

In [114]:
#타이틀
title_els = soup.select('h3.h_lst > span.blind')
# title_els

In [106]:
# 단위들: div.head_info span.blind
unit_els=soup.select('div.head_info>span>span.blind')
len(unit_els)
units = [unit_el.string for unit_el in unit_els]
units.insert(7,'')
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [110]:
#상승/하락 div.head_info span.blind
trend_els=soup.select('div.head_info > span.blind')
# trend_els

In [115]:
len(title_els), len(price_els),len(units),len(trend_els)

(12, 12, 12, 12)

In [118]:
for title,price,unit,trend in zip (title_els,price_els,units,trend_els):
        print("{}:{}{}-{}".format(title.text, price.text, unit, trend.text))

미국 USD:1,417.70원-상승
일본 JPY(100엔):889.17원-상승
유럽연합 EUR:1,635.60원-상승
중국 CNY:210.09원-상승
달러/일본 엔:159.2400엔-상승
유로/달러:1.1541달러-하락
영국 파운드/달러:1.3507달러-하락
달러인덱스:99.7100-상승
WTI:83.2달러-상승
휘발유:1863.92원-하락
국제 금:4441.1달러-상승
국내 금:200855.05원-상승

In [132]:
import pandas as pd
data =[]
for title,price,unit,trend in zip (title_els,price_els,units,trend_els):
        data.append({'title':title.text,
                     'price':float(price.text.replace(',','')),
                     'unit':unit,
                     'trend':trend.text})
pd.DataFrame(data)#.to_csv('data/file.csv',index=False)
data

[{'title': '미국 USD', 'price': 1417.7, 'unit': '원', 'trend': '상승'},
 {'title': '일본 JPY(100엔)', 'price': 889.17, 'unit': '원', 'trend': '상승'},
 {'title': '유럽연합 EUR', 'price': 1635.6, 'unit': '원', 'trend': '상승'},
 {'title': '중국 CNY', 'price': 210.09, 'unit': '원', 'trend': '상승'},
 {'title': '달러/일본 엔', 'price': 159.24, 'unit': '엔', 'trend': '상승'},
 {'title': '유로/달러', 'price': 1.1541, 'unit': '달러', 'trend': '하락'},
 {'title': '영국 파운드/달러', 'price': 1.3507, 'unit': '달러', 'trend': '하락'},
 {'title': '달러인덱스', 'price': 99.71, 'unit': '', 'trend': '상승'},
 {'title': 'WTI', 'price': 83.2, 'unit': '달러', 'trend': '상승'},
 {'title': '휘발유', 'price': 1863.92, 'unit': '원', 'trend': '하락'},
 {'title': '국제 금', 'price': 4441.1, 'unit': '달러', 'trend': '상승'},
 {'title': '국내 금', 'price': 200855.05, 'unit': '원', 'trend': '상승'}]

In [134]:
data=[]
for title,price,unit,trend in zip (title_els,price_els,units,trend_els):
    data.append([title.text,float(price.text.replace(',','')),unit,trend.text])
pd.DataFrame(data, columns=['title','price','unit','trend'])
data

[['미국 USD', 1417.7, '원', '상승'],
 ['일본 JPY(100엔)', 889.17, '원', '상승'],
 ['유럽연합 EUR', 1635.6, '원', '상승'],
 ['중국 CNY', 210.09, '원', '상승'],
 ['달러/일본 엔', 159.24, '엔', '상승'],
 ['유로/달러', 1.1541, '달러', '하락'],
 ['영국 파운드/달러', 1.3507, '달러', '하락'],
 ['달러인덱스', 99.71, '', '상승'],
 ['WTI', 83.2, '달러', '상승'],
 ['휘발유', 1863.92, '원', '하락'],
 ['국제 금', 4441.1, '달러', '상승'],
 ['국내 금', 200855.05, '원', '상승']]

### 2)이번주 로또번호 출력
- 방법2에서 User Agent를 추가하여 soup생성 
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto(다음에서 lotto검색)
````
        1236회(2026.08.08 추첨)
        당첨번호 [12,18,21,29,34,38]
        보너스 10
````

In [139]:
#방법1
import requests
from bs4 import BeautifulSoup
url='https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response=requests.get(url)
print('response의 상태 :',response.status_code)
soup=BeautifulSoup(response.text, 'html.parser')
soup

response의 상태 : 200

<!DOCTYPE html>

<html lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<meta content="text/html;charset=utf-8" http-equiv="content-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="off" name="autocomplete"/>
<meta content="always" name="referrer"/>
<meta content="telephone=no,address=no,email=no" name="format-detection">
<meta content="lotto – Daum 검색" property="og:title"/>
<meta content="https://search.daum.net/search?w=tot&amp;DA=YZR&amp;t__nil_searchbox=btn&amp;q=lotto" property="og:url"/>
<meta content="Daum 검색에서 lotto에 대한 최신정보를 찾아보세요." property="og:description"/>
<meta content="https://search1.daumcdn.net/search/statics/common/img/2026/daum_og.png" property="og:image"/>
<meta content="다음검색" property="og:site_name"/>
<link href="https://search1.daumcdn.net/search/statics/common/img/2026/0303/favicon.ico" rel="shortcut icon"/>
<link href="//sl.search.daum.net/" rel="preconnect"/>
<link href="//ssl.daumcdn.net/" rel="preconnect"/>
<link href="//t1.daumcdn.net/" rel="preconnect"/>
<link href="//wat.ad.daum.net/" rel="preconnect"/>
<link href="//track.tiara.daum.net/" rel="preconnect"/>
<link href="//webid.ad.daum.net/" rel="preconnect"/>
<link href="//webid.kakao.com/" rel="preconnect"/>
<title>lotto – Daum 검색</title>
<link href="//search.daum.net/OpenSearch.xml" rel="search" title="Daum" type="application/opensearchdescription+xml"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_common.0803091025.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_component.0721094041.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/pm_common.0724103702.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/q_comm.0625022346.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/dds-workspace/css/2.2.1/dds.min.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20260622160606/cubic.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_collection.0202081129.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_collection2.0706103558.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_lottoColl.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_n0nlColl.0213073457.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_adLinkColl.0910022655.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/em1Coll.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="https://search1.daumcdn.net/search/statics/common/css/2026/p_shoppingColl.0803012615.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_newsColl.0803092251.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/p_poiColl.0728123112.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2026/rtlColl.0708073340.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
var uk = "7c502c44-02b7-4313-9ae1-4b1554c913e5";
var mk = "7c502c44-02b7-4313-9ae1-4b1554c913e5";
var ksk = "7c502c44-02b7-4313-9ae1-4b1554c913e5";
var ud = "";
var uuid = "";
var adid = "";
var adid_enabled = "N";
var viewio = "i";
var viewsite = "";
var ServerTime = "20260812152707";
var utf8Query = encodeURIComponent("lotto");
var topQuery = "lotto";
var backQuery = encodeURIComponent("lotto");
var login_yn = "N";
var encodeType = "2";
var refCode = "";
var bucketType = "";
var name_check = "0";
var mobileDevice = "N";
var param_w = "tot";
var param_da = "YZR";
var paramCfg = "";
var param_cnucc = "";
var tpl_cfg = "";
var cnucc = "";
var usrIp = "175.198.89.213";
var isDetailTab = "N";
var schSort = "";
var existMobileTabYn = "N";
var width_over_620 = "Y";
var sPageLoadedmsTime =  142 ;
var isReleaseMode = '';
var isTotDebugMode = false;
var KAKAO_ACCOUNT_ID_CONNECTED = "N";
var displayInfo = {"SER":[{"code":"LOT","doc_count":1},{"code":"0NL","doc_count":9},{"code":"0SC","doc_count":2},{"code":"0LL","doc_count":2},{"code":"DIA","doc_count":1},{"code":"TWA","doc_count":1},{"code":"EM1","doc_count":0},{"code":"TWD","doc_count":5},{"code":"IVR","doc_count":3},{"code":"MS2","doc_count":1},{"code":"LB2","doc_count":1},{"code":"SNY","doc_count":8},{"code":"VOI","doc_count":6},{"code":"VOO","doc_count":10},{"code":"DNS","doc_count":4},{"code":"GG2","doc_count":1},{"code":"IIM","doc_count":20},{"code":"CLO","doc_count":1}],"SGR":[{"code":"NSJ","doc_count":0},{"code":"DCC","doc_count":0},{"code":"RTL","doc_count":10},{"code":"KYW","doc_count":10},{"code":"1DR","doc_count":10},{"code":"BXJ","doc_count":10},{"code":"RSJ","doc_count":0}],"SUI":[],"CUT":[{"code":"TGV","doc_count":0}]};
var usr4 = "NSJ0_LOT1_0NL9_0SC2_0LL2_DIA1_TWA1_EM10_TWD5_IVR3_MS21_LB21_SNY8_VOI6_VOO10_DNS4_GG21_IIM20_0GL0_DCC0_RTL10_KYW10_1DR10_BXJ10_RSJ0_CLO1";
var slCallType = "sync";
var pageLoadedTime = 0;
var startTime = new Date().getTime();
var sugLocCode = "";
var searchLog = {
uc: 0,
clickCount: 0,
dl: ""
};
var SEARCHLOGDOMAIN = "\/\/sl.search.daum.net";
var CNUCC_URL = "https:\/\/harm.search.daum.net\/v2\/api\/report-harm";
var ASUG_URL = "\/\/ninstant.search.daum.net\/suggest\/index.daum";
var AMADO_URL = "\/\/search1.daumcdn.net\/search\/statics\/common\/js\/fe\/amado-workspace\/pc\/3.0.1\/main.js";
var SF = {
phase: "prod",
userQueryParamW: "tot",
platform: "pc",
iam: {
clean: false,
geo: false,
login: false,
loginUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do",
adult: false,
adultUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do?service=adult_service\u0026url=https%3A%2F%2Fsearch.daum.net%2Fsearch%3FDA%3DYZR%26q%3Dlotto%26realname_redirect%3D1%26t__nil_searchbox%3Dbtn%26w%3Dtot"
},
ua: {"ua":"python-requests/2.28.1","browser":{"name":"","version":{"info":"","major":0,"minor":0,"patch":0}},"device":"","os":{"name":"unix","version":{"info":"","major":0,"minor":0,"patch":0}},"platform":"pc","app":{"isDaumapp":false,"isKakao":false,"version":{"info":"","major":0,"minor":0,"patch":0}}}
};
SF.ua.app.isApp = SF.ua.app.isDaumapp;
SF.ua.os[SF.ua.os.name] = true;
SF.ua.browser[SF.ua.browser.name] = true;
SF.loadModuleList = {"amcharts":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/amcharts.20190321202015.min.js","calendar":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/calendar/module.p.calendar.20210312112039.min.js","chart":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/chart.20200602182334.min.js","kakaosdk":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/kakaosdk.20230811110443.min.js","kakaotv":"//tv.kakao.com/player/script/sdk/player_api.min.js","ks":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/ks/module.p.ks.20221122154101.min.js","pagenavigation":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/pagenavigation/module.p.pagenavigation.20220705092744.min.js","v3":"//ssl.daumcdn.net/dmaps/map_js_init/v3.js","youtube":"//www.youtube.com/player_api"};
var SD = {};
var SG = {};
var C = {};
var T = {};
var SL = {
mkeyLog: function(){},
freelog: {
send: function(){}
},
dexposeLog: {
send: function(){}
},
xscrollLog: function(){}
};
var smartLog = function(){};
</script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/polyfill/p-legacy/1.4.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/logger/1.2.0/main.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/vendor/p/1.1.1/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/search-log/p/1.5.1/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/module/1.52.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/library/1.50.0/remoteEntry.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/runtime/1.48.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20260622160606/cubic.min.js?o=p" type="text/javascript"></script>
<script src="//t1.daumcdn.net/tiara/js/v1/tiara-1.2.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
(function(SF){
SF.tiaraTracker.setDefaultConfig();
})(window.SF || {});
</script>
</meta></head>
<body class="daum unix wide pc">
<script type="text/javascript">
SL.mkeyLog();
</script>
<nav class="d_direct" id="daumIndex">
<a class="link_direct" href="#daumBody">본문 바로가기</a>
<a class="link_direct" href="#daumGnb">메뉴 바로가기</a>
</nav>
<div id="saq" style="display:none">lotto</div>
<div class="sch_tab_tot" id="daumWrap">
<header id="daumHead">
<div class="d_head">
<h1 class="screen_out">다음</h1>
<h2 class="screen_out">검색</h2>
<div class="inner_header" id="innerHeader">
<form class="d_sch" id="daumSearch" method="get" name="search">
<fieldset class="fld_total">
<legend class="screen_out">검색폼</legend>
<input id="nil_suggest" name="nil_suggest" type="hidden" value="btn"/>
<input id="nil_ch" name="nil_ch" type="hidden" value=""/>
<input name="rtupcoll" type="hidden" value=""/>
<input name="w" type="hidden" value="tot"/>
<input name="m" type="hidden" value=""/>
<input id="f" name="f" type="hidden" value=""/>
<input name="lpp" type="hidden" value=""/>
<input name="DA" type="hidden" value="SBC"/>
<input name="sug" type="hidden" value=""/>
<input name="sq" type="hidden" value=""/>
<input name="o" type="hidden" value=""/>
<input name="sugo" type="hidden" value=""/>
<div class="box_searchbar">
<div class="inner_searchbar">
<a aria-label="Daum 메인페이지로 가기" class="link_service" data-target="_top" href="https://www.daum.net/" id="daumLogo" onclick='smartLog(this, "e=1&amp;dc=MLC", event);' target="_top" title="Daum 메인페이지로 가기">
<svg aria-hidden="true" fill="none" height="40" viewbox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_496_626)">
<mask height="24" id="mask0_496_626" maskunits="userSpaceOnUse" style="mask-type:alpha" width="24" x="10" y="8">
<path d="M22 14.36C25.1152 14.36 27.6352 17.072 27.5152 20.2136C27.4024 23.2016 24.8536 25.64 21.8632 25.64H17.9176C17.6536 25.64 17.4376 25.424 17.4376 25.16V14.84C17.4376 14.576 17.6536 14.36 17.9176 14.36H21.9976M22 8H12.4C11.6056 8 10.96 8.6456 10.96 9.44V30.56C10.96 31.3544 11.6056 32 12.4 32H22C28.6264 32 34 26.6264 34 20C34 13.3736 28.6264 8 22 8Z" fill="white"></path>
</mask>
<g mask="url(#mask0_496_626)">
<rect fill="url(#paint0_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint1_radial_496_626)" height="24" transform="rotate(-180 33.9999 32)" width="23.04" x="33.9999" y="32"></rect>
<rect fill="url(#paint2_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint3_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
<rect fill="url(#paint4_radial_496_626)" height="24" width="23.04" x="10.96" y="8"></rect>
</g>
</g>
<defs>
<radialgradient cx="0" cy="0" gradienttransform="translate(11.32 8.48) rotate(47.9943) scale(27.6149 18.2643)" gradientunits="userSpaceOnUse" id="paint0_radial_496_626" r="1">
<stop stop-color="#1E84FF"></stop>
<stop offset="1" stop-color="#1E84FF"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(50.6799 32) rotate(90) scale(32.76 116.718)" gradientunits="userSpaceOnUse" id="paint1_radial_496_626" r="1">
<stop offset="0.0710642" stop-color="#F95F65"></stop>
<stop offset="0.255335" stop-color="#F95F97" stop-opacity="0.85"></stop>
<stop offset="0.488545" stop-color="#E952BE" stop-opacity="0.3"></stop>
<stop offset="0.64993" stop-color="#1E84FF" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(31.12 11.96) rotate(133.452) scale(12.5628 13.3382)" gradientunits="userSpaceOnUse" id="paint2_radial_496_626" r="1">
<stop stop-color="#22BB64"></stop>
<stop offset="0.598459" stop-color="#22BBA4" stop-opacity="0.5"></stop>
<stop offset="1" stop-color="#61BACA" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(34 21.92) rotate(-170.538) scale(11.6789 14.112)" gradientunits="userSpaceOnUse" id="paint3_radial_496_626" r="1">
<stop stop-color="#2FD800"></stop>
<stop offset="1" stop-color="#12EB1A" stop-opacity="0"></stop>
</radialgradient>
<radialgradient cx="0" cy="0" gradienttransform="translate(29.32 29.72) rotate(-126.545) scale(12.6962 17.5254)" gradientunits="userSpaceOnUse" id="paint4_radial_496_626" r="1">
<stop stop-color="#FFC622"></stop>
<stop offset="0.524982" stop-color="#FFC622" stop-opacity="0.6"></stop>
<stop offset="1" stop-color="#FFC622" stop-opacity="0"></stop>
</radialgradient>
<clippath id="clip0_496_626">
<rect fill="white" height="24" transform="translate(10 8)" width="24"></rect>
</clippath>
</defs>
</svg>
</a>
<input autocomplete="off" class="tf_keyword" id="q" maxlength="255" name="q" title="검색어 입력" type="text" value="lotto"/>
<button class="btn_reset" id="btnResetHeader" onclick="smartLog(this, 'pg=1&amp;p=2&amp;r=1&amp;rc=1&amp;dc=SBC&amp;at=func', event);" title="검색어 지우기" type="button">
<span class="ico_ksg">입력삭제</span>
</button>
<button aria-label="가상키보드 열기" class="btn_vkey" id="VKIBtn" onclick="smartLog(this, 'pg=1&amp;p=1&amp;r=1&amp;rc=1&amp;dc=BFJ&amp;at=func', event);" title="가상키보드 열기" type="button">
<svg fill="none" height="28" width="28" xmlns="http://www.w3.org/2000/svg">
<rect height="15" rx="4" stroke="currentColor" stroke-width="2" width="24" x="2" y="6.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="9" x="9.5" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="16.5"></rect>
</svg>
</button>
<button aria-label="검색" class="btn_ksearch" id="daumBtnSearch" title="검색" type="submit">
<svg fill="currentColor" height="28" viewbox="0 0 28 28" width="28" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M12.5 4C17.1944 4 21 7.80558 21 12.5C21 14.501 20.3064 16.3389 19.1494 17.791C19.2295 17.8353 19.3051 17.891 19.373 17.959L24.373 22.959C24.7636 23.3495 24.7636 23.9825 24.373 24.373C23.9825 24.7636 23.3495 24.7636 22.959 24.373L17.959 19.373C17.891 19.3051 17.8353 19.2295 17.791 19.1494C16.3389 20.3064 14.501 21 12.5 21C7.80558 21 4 17.1944 4 12.5C4 7.80558 7.80558 4 12.5 4ZM12.5 6C8.91015 6 6 8.91015 6 12.5C6 16.0899 8.91015 19 12.5 19C16.0899 19 19 16.0899 19 12.5C19 8.91015 16.0899 6 12.5 6Z"></path>
</g>
</svg>
</button>
</div>
</div>
</fieldset>
<div class="box_suggest" id="daumSuggestTop"><div id="suggestBox"></div></div>
</form>
<div id="wrapMinidaum"></div>
</div>
<div id="daumGnb">
<div class="tab_dynamic tab_flex">
<ul class="list_tab">
<li class="on">
<span class="screen_out">선택된 항목</span>
<a class="tab_tit" href="?w=tot&amp;q=lotto&amp;DA=NTB" onclick="smartLog(this, 'pg=1&amp;r=1&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event);"><span class="inner_tab">통합</span></a>
</li>
<li class="">
<a class="tab_tit" href="?w=fusion&amp;nil_search=btn&amp;DA=NTB&amp;p=2&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=2&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
통합웹</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=site&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;lpp=10&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=3&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
사이트</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://www.melon.com/search/total/index.htm?q=lotto&amp;ref=W10060" onclick="smartLog(this, 'pg=1&amp;r=4&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
멜론뮤직<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=book&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=5&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
책</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://shoppinghow.kakao.com/search/lotto/&amp;srchhow=Cexpo" onclick="smartLog(this, 'pg=1&amp;r=6&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
쇼핑<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=vclip&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=7&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
동영상</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=8&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
뉴스</span>
</a>
</li>
</ul>
<div class="more_dynamic more_search">
<button class="btn_tab" id="gnbToggleBtn" title="더보기" type="button">
<span class="ico_ksg">더보기/접기</span>
</button>
<ul class="list_more">
<li class="">
<a class="tab_tit" href="https://map.kakao.com/?from=total&amp;nil_suggest=btn&amp;tab=place&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=9&amp;p=2&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
지도<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=img&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=lotto" onclick="smartLog(this, 'pg=1&amp;r=10&amp;p=2&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
이미지</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="http://dic.daum.net/search.do?q=lotto" onclick="smartLog(this, 'pg=1&amp;r=11&amp;p=2&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
어학사전<span class="ico_ksg ico_outlink">새창</span>
</span>

In [145]:
#방법2
from urllib.request import urlopen, Request
headers={'User-Agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request= Request(url, headers=headers)

response = urlopen(request)
print('response의 상태 :', response.status)
soup=BeautifulSoup(response, 'html.parser')
#soup

response의 상태 : 200

In [160]:
#1236회(2026.08.08 추첨)
#당첨번호 [12,18,21,29,34,38]
#보너스 10
times=soup.select_one('div.prize>strong>span.f_red').text
date= soup.select_one('div.prize>span.date').text
title1=soup.select_one('div.prize > strong').text[-4:]
lotto_numbers=soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lotto_numbers=soup.select('div.lottonum > span.ball')[:-2]
title2=soup.select_one('div.lottonum span.screen_out').text
bonus_number=soup.select_one('div.lottonum > span.bg_ball1').text
print(times, date)
print(title1,[int(numbers.text) for numbers in lotto_numbers])
print(title2, bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [164]:
# 위의 select계열 함수를 find계열함수로 변경하여 구현해 보기
# times = soup.select_one('div.prize span.f_red').text
prize = soup.find('div', class_='prize')
times = prize.find('span', class_='f_red').text

# date = soup.select_one('div.prize > span.date').text
date = prize.find('span', class_='date').text

# title1 = soup.select_one('div.prize > strong').text[-4:]
title1 = prize.find('strong').text[-4:]

# lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
lottonum = soup.find('div', class_='lottonum')
lotto_numbers = lottonum.find_all('span', class_='ball')[:-2]

# title2 = soup.select_one('div.lottonum span.screen_out').text
title2 = lottonum.find('span', class_='screen_out').text

# bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number = lottonum.find('span', class_='bg_ball1').text

print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2, bonus_number)

'당첨번호'

### 3)다음 뉴스 검색리스트 
```
no title  href
0 타이틀1  http://~
1 타이틀2  http://~
2 타이틀3  http://~

```

In [166]:
# 방법1
import requests
from bs4 import BeautifulSoup
word ='비트코인'
url=f'https://search.daum.net/search?nil_suggest=btn&w=news&DA=PGD&cluster=y&q={word}'
print(url)
response=requests.get(url)
print(response.status_code)
soup=BeautifulSoup(response.text, 'html.parser')

https://search.daum.net/search?nil_suggest=btn&w=news&DA=PGD&cluster=y&q=비트코인
200

In [173]:
#방법2 
from urllib.request import urlopen, Request
from urllib.parse import quote
word=quote('비트코인')
url=f'https://search.daum.net/search?nil_suggest=btn&w=news&DA=PGD&cluster=y&q={word}'
print(url)
headers={'User-Agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request= Request(url, headers=headers)
request=Request(url)
request.add_header('User-Agent',
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response =urlopen(request)
print(response.status)
soup=BeautifulSoup(response, 'html.parser')
#soup

https://search.daum.net/search?nil_suggest=btn&w=news&DA=PGD&cluster=y&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8
200

In [185]:
items_find_list=[]#검색한 결과를 담을 dict리스트 
items_el = soup.select('div.item-title> strong.tit-g.clamp-g >a')
for idx, item in enumerate(items_el):
    print(idx, item.text)
    items_find_list.append({'no':idx, 
                           'title':item.text,
                           'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list)

0  9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑
1  [코인뉴스] 비트코인 박스권 지속…다음 변수는?
2  [코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅
3  9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망
4  [코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속
5  [08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴
6  트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다
7  금리 공포 걷히자 "금값 조정 끝났다"… 비트코인은 나 홀로 약세
8  [아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보
9  비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜]

,no,title,link
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
2,2,[코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅,http://v.daum.net/v/20260812163039451
3,3,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645
4,4,[코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속,http://v.daum.net/v/20260812103841887
5,5,"[08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴",http://v.daum.net/v/20260812080815138
6,6,"트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다",http://v.daum.net/v/20260811144238992
7,7,"금리 공포 걷히자 ""금값 조정 끝났다""… 비트코인은 나 홀로 약세",http://v.daum.net/v/20260812164709172
8,8,[아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보,http://v.daum.net/v/20260812082712570
9,9,비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜],http://v.daum.net/v/20260812082137419

In [184]:
items_find_list = [] #검색한 결과를 담을 2차원 리스트 
items_el=soup.select('div.item-title > strong.tit-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
pd.DataFrame(items_find_list, columns=['순번', '기사제목','링크'])

,순번,기사제목,링크
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
2,2,[코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅,http://v.daum.net/v/20260812163039451
3,3,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645
4,4,[코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속,http://v.daum.net/v/20260812103841887
5,5,"[08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴",http://v.daum.net/v/20260812080815138
6,6,"트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다",http://v.daum.net/v/20260811144238992
7,7,"금리 공포 걷히자 ""금값 조정 끝났다""… 비트코인은 나 홀로 약세",http://v.daum.net/v/20260812164709172
8,8,[아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보,http://v.daum.net/v/20260812082712570
9,9,비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜],http://v.daum.net/v/20260812082137419

In [190]:
# 다음 뉴스 검색 함수 (원하는 키워드, 원하는 페이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword, page):
    'keyword로 해당 page에 검색한 결과 dict list return'
    #url=f'https://search.daum.net/search?nil_suggest=btn&w=news&DA=PGD&cluster=y&q={keyword}&p={page}'
    url = 'https://search.daum.net/search?w=news'
    params={'q':keyword, 'p':page}
    response=request.get(url, params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    items_el=soup.select('div.item-title > strong.tit-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10+idx,'title':item.text,'link':item.attrs.get('href')})
        return items_find_list

In [191]:
collect_list('꽃',2)

AttributeError: 'Request' object has no attribute 'get'