In [2]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:98% !important;}
div.cell.code_cell.rendered{width:95%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
.inner_cell{font-size:22pt;}
div.text_cell_render pre code {font-size:22pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

# 1. 데이타셋

In [9]:
import pandas as pd 
url ='https://raw.githubusercontent.com/4aix/data/refs/heads/master/ch13_apt_fillna_median.csv'
df=pd.read_csv(url)
df.sample()

     지역명   평당분양가격    연도  월
1943  광주  18146.7  2023  7

- 지역명2: 지역명필드를 라벨인코딩하여 추가 (df) 
- 독립변수 (X):지역명2, 연도, 월 
- 종속변수 (y):평당분양가격 
- 독립변수와 종속변수(reshape)의 스케일 조정
    * 정규화(MinMaxScaler)작업후 : 지역명 2m, 연도m, 월m 컬럼, 평당분양가격m => df m 
    * 표준화 (StandardScaler) 작업후: 지역명2s, 연도s, 월s컬럼, 평당분양가격s => df_s 
    => 지역명, 연도, 월, 지역명2, 지역명2m, 연도m, 월m, 평당분양가격m, 지역명2s, 연도s, 월s컬럼, 평당분양가격s

# 2. 지역명의 라벨인코딩

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['지역명2']= encoder.fit_transform(df['지역명'])
df.head(20)

   지역명   평당분양가격    연도   월  지역명2
0   서울  18189.0  2013  12     8
1   부산   8111.0  2013  12     7
2   대구   8080.0  2013  12     5
3   인천  10204.0  2013  12    11
4   광주   6098.0  2013  12     4
5   대전   8321.0  2013  12     6
6   울산   8090.0  2013  12    10
7   경기  10855.0  2013  12     1
8   세종   7601.0  2013  12     9
9   강원   6230.0  2013  12     0
10  충북   6589.0  2013  12    16
11  충남   6365.0  2013  12    15
12  전북   6282.0  2013  12    13
13  전남   5678.0  2013  12    12
14  경북   6168.0  2013  12     3
15  경남   6473.0  2013  12     2
16  제주   7674.0  2013  12    14
17  서울  17925.0  2014   1     8
18  부산   8111.0  2014   1     7
19  대구   8080.0  2014   1     5

# 3. MinMax Scaling

In [35]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np

X_data=df[['지역명2', '연도', '월']]
y_data=df[['평당분양가격']]  # x 값은 2차원인데 y 값은 2차원이 아니니까 배열로 만들어서 2차원을 만들어 준다.

scaler_X=MinMaxScaler()
scaler_y = MinMaxScaler()

df[['지역명2m','연도m','월m']] = scaler_X.fit_transform(X_data)
df[['평당분양가격m']]=scaler_y.fit_transform(y_data)

df.head(4)
#np.column_stack([scaler_X, scaler_y])

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,월m 컬럼,지역명2s,연도s,월s 컬럼,평당분양가격s
0,서울,18189.0,2013,12,8,0.5000,0.0,1.0,0.328198,1.0,0.000000,-1.875367,1.62196,1.168591
1,부산,8111.0,2013,12,7,0.4375,0.0,1.0,0.065274,1.0,-0.204124,-1.875367,1.62196,-0.728312
2,대구,8080.0,2013,12,5,0.3125,0.0,1.0,0.064466,1.0,-0.612372,-1.875367,1.62196,-0.734147
3,인천,10204.0,2013,12,11,0.6875,0.0,1.0,0.119878,1.0,0.612372,-1.875367,1.62196,-0.334363

# 4. StandardScaling

In [36]:
X_data=df[['지역명2', '연도', '월']]
y_data=df[['평당분양가격']]

scaler_X = StandardScaler()
stan_scaled_X_data = scaler_X.fit_transform(X_data)
scaler_y = StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)

df[['지역명2s','연도s','월s']] = scaler_X.fit_transform(X_data)
df[['평당분양가격s']]=scaler_y.fit_transform(y_data)

df.head(4)

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,월m 컬럼,지역명2s,연도s,월s 컬럼,평당분양가격s,월s
0,서울,18189.0,2013,12,8,0.5000,0.0,1.0,0.328198,1.0,0.000000,-1.875367,1.62196,1.168591,1.62196
1,부산,8111.0,2013,12,7,0.4375,0.0,1.0,0.065274,1.0,-0.204124,-1.875367,1.62196,-0.728312,1.62196
2,대구,8080.0,2013,12,5,0.3125,0.0,1.0,0.064466,1.0,-0.612372,-1.875367,1.62196,-0.734147,1.62196
3,인천,10204.0,2013,12,11,0.6875,0.0,1.0,0.119878,1.0,0.612372,-1.875367,1.62196,-0.334363,1.62196

# 5. 지역명을 원핫인코딩

In [34]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['지역명2'] =to_categorical(encoder)

NameError: name 'to_categorical' is not defined